//@ui5-bundle sap/ushell/components/workPageRuntime/Component-preload.js
// Copyright (c) 2009-2025 SAP SE, All Rights Reserved
sap.ui.predefine("sap/ushell/components/workPageRuntime/Component", ["sap/ui/core/UIComponent"],t=>{"use strict";return t.extend("sap.ushell.components.workPageRuntime.Component",{metadata:{manifest:"json",library:"sap.ushell",interfaces:["sap.ui.core.IAsyncContentCreation"]},getNavigationDisabled:function(){const t=this.getComponentData()||{};return!!t.navigationDisabled},hideRuntime:function(){this.getRootControl().getController().hideRuntime()},onRouteMatched:function(){this.getRootControl().getController().onRouteMatched()}})});
// Copyright (c) 2009-2025 SAP SE, All Rights Reserved
sap.ui.predefine("sap/ushell/components/workPageRuntime/controller/WorkPageRuntime.controller", ["sap/base/Log","sap/ui/core/mvc/Controller","sap/ushell/utils/workpage/WorkPageService","sap/base/util/deepExtend","sap/ushell/EventHub","sap/ushell/components/pages/controller/PagesAndSpaceId","sap/ushell/Config","sap/ushell/Container"],(e,t,o,a,n,i,r,s)=>{"use strict";return t.extend("sap.ushell.components.workPageRuntime.controller.WorkPageRuntime",{onInit:function(){const e=s.getRendererInternal();this.oWorkPageService=new o;this.oWorkPageNavContainer=this.byId("workPageNavContainer");this.oEmptyPage=this.byId("emptyPage");this._oWorkPageBuilderComponentCreatedPromise=new Promise((e,t)=>{this._oWorkPageBuilderComponentResolve=e;this._oWorkPageBuilderComponentReject=t});this._oInitPromise=this._getPageId().then(t=>{this._sPageId=t;return this._onWorkPageLoad().finally(()=>{n.emit("CenterViewPointContentRendered");if(!this.getOwnerComponent().getNavigationDisabled()){this.oContainerRouter=e.getRouter();this.oContainerRouter.getRoute("home").attachMatched(this.onRouteMatched.bind(this,false));this.oContainerRouter.getRoute("openFLPPage").attachMatched(this.onRouteMatched.bind(this,false))}})}).catch(this._handleErrors.bind(this))},_navigate:function(){this.oWorkPageNavContainer.to(this.byId("workPage"))},onWorkPageBuilderCreated:function(e){this._oWorkPageBuilderComponent=e.getParameter("component");this._oWorkPageBuilderComponentResolve(this._oWorkPageBuilderComponent)},_handleErrors:function(t){e.error("An error occurred while loading the page",t);this.oWorkPageNavContainer.to(this.byId("errorPage"))},onRouteMatched:function(){e.debug("cep/editMode: on Route matched","Work Page runtime");return this._getPageId().then(e=>{this._sPageId=e;return this._onWorkPageLoad()}).catch(this._handleErrors.bind(this)).then(()=>{n.emit("CloseFesrRecord",Date.now())})},_onWorkPageLoad:async function(){this._oLoadWorkPageAndVisualizationsPromise=this.oWorkPageService.loadWorkPageAndVisualizations(this._sPageId,true);const[e,t]=await Promise.all([this._oWorkPageBuilderComponentCreatedPromise,this._oLoadWorkPageAndVisualizationsPromise]);this._oOriginalData=a({},t);await e.setPageData(t);this._navigate()},_getPageId:function(){if(r.last("/core/workPages/myHome/pageId")){return Promise.resolve(r.last("/core/workPages/myHome/pageId"))}return i.getPageAndSpaceId().then(e=>e.pageId)},hideRuntime:function(){e.debug("cep/editMode: navigate to empty page","Page runtime");this.oWorkPageNavContainer.to(this.oEmptyPage)}})});
sap.ui.require.preload({
	"sap/ushell/components/workPageRuntime/manifest.json":'{"_version":"1.39.0","sap.app":{"id":"sap.ushell.components.workPageRuntime","applicationVersion":{"version":"1.141.1"},"ach":"CA-FLP-FE-UI","type":"component","title":""},"sap.ui":{"fullWidth":false,"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"componentUsages":{"pageBuilder":{"settings":{"id":"workPageBuilderComponent"},"name":"sap.ushell.components.workPageBuilder","lazy":true}},"componentName":"sap.ushell.components.workPageRuntime","rootView":{"viewName":"sap.ushell.components.workPageRuntime.view.WorkPageRuntime","type":"XML","id":"workPageRuntimeView","async":true},"dependencies":{"minUI5Version":"1.99","libs":{"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true}}}',
	"sap/ushell/components/workPageRuntime/view/WorkPageRuntime.view.xml":'<mvc:View\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n    controllerName="sap.ushell.components.workPageRuntime.controller.WorkPageRuntime"\n    height="100%"\n    core:require="{\n        mobileLibrary: \'sap/m/library\'\n    }"><NavContainer id="workPageNavContainer"><Page\n            id="workPage"\n            busy="{= !${/loaded}}"\n            enableScrolling="false"\n            showHeader="false"\n            backgroundDesign="{= mobileLibrary.PageBackgroundDesign.Transparent }"><core:ComponentContainer\n                id="workPageBuilderComponentContainer"\n                height="100%"\n                usage="pageBuilder"\n                manifest="true"\n                async="true"\n                componentCreated="onWorkPageBuilderCreated" /></Page><Page\n            id="errorPage"\n            showHeader="false"><IllustratedMessage\n                illustrationType="{= mobileLibrary.IllustratedMessageType.PageNotFound }" /></Page><Page\n            id="emptyPage"\n            showHeader="false"\n            backgroundDesign="{= mobileLibrary.PageBackgroundDesign.Transparent }"/></NavContainer></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
