/*!
 * TinyMCE Language Pack
 *
 * Copyright (c) 2023 Ephox Corporation DBA Tiny Technologies, Inc.
 * Licensed under the Tiny commercial license. See https://www.tiny.cloud/legal/
 */
tinymce.addI18n("fr_FR", {
  "TinyComments": "Petits commentaires",
  "Comments": "Commentaires",
  "Add comment": "Ajouter un commentaire",
  "Show comments": "Afficher les commentaires",
  "Delete all conversations": "Supprimer toutes les conversations",
  "Delete conversation": "Supprimer la conversation",
  "Delete": "Supprimer",
  "Clear": "Effacer",
  "Edit": "Modifier",
  "Comment": "Commentaire",
  "Save": "Enregistrer",
  "Add comment...": "Ajouter un commentaire...",
  "Delete all conversations in the content? This cannot be undone.": "Voulez-vous supprimer toutes les conversations dans le contenu\xa0? Vous ne pourrez pas revenir en arri\xe8re.",
  "Are you sure you want to delete this comment?": "\xcates-vous s\xfbr de vouloir supprimer ce commentaire ?",
  "Delete this conversation?": "Supprimer cette conversation ?",
  "You are not allowed to edit this comment": "Vous n'\xeates pas autoris\xe9 \xe0 modifier ce commentaire",
  "You are not allowed to delete all the conversations": "Vous n'\xeates pas autoris\xe9 \xe0 supprimer toutes les conversations",
  "You are not allowed to delete this conversation": "Vous n'\xeates pas autoris\xe9 \xe0 supprimer cette conversation",
  "You are not allowed to delete this comment": "Vous n'\xeates pas autoris\xe9 \xe0 supprimer ce commentaire",
  "1 comment will be deleted. You can't undo this action.": "1 commentaire sera supprim\xe9. Vous ne pouvez pas annuler cette action.",
  "{0} comments will be deleted. You can't undo this action.": "{0} commentaires seront supprim\xe9s. Vous ne pouvez pas annuler cette action.",
  " (edited)": "(modifi\xe9)",
  "a moment ago": "il y a un instant",
  "1 minute ago": "il y a 1 minute",
  "{0} minutes ago": "il y a {0} minutes",
  "1 hour ago": "il y a 1 heure",
  "{0} hours ago": "il y a {0} heures",
  "1 day ago": "il y a 1 jour",
  "{0} days ago": "il y a {0} jours",
  "1 week ago": "il y a 1 semaine",
  "{0} weeks ago": "il y a {0} semaines",
  "1 month ago": "il y a 1 mois",
  "{0} months ago": "il y a {0} mois",
  "1 year ago": "il y a 1 an",
  "{0} years ago": "il y a {0} ans",
  "SHOW MORE": "AFFICHER PLUS",
  "SHOW LESS": "AFFICHER MOINS",
  "Resolve conversation": "R\xe9soudre la conversation",
  "Resolve": "R\xe9soudre",
  "Resolve this conversation?": "R\xe9soudre cette conversation ?",
  "1 comment will be resolved. You can't undo this action.": "1 commentaire sera r\xe9solu. Vous ne pouvez pas annuler cette action.",
  "{0} comments will be resolved. You can't undo this action.": "{0} commentaires seront supprim\xe9s. Vous ne pouvez pas annuler cette action.",
  "You are not allowed to resolve this conversation": "Vous n'\xeates pas autoris\xe9 \xe0 r\xe9soudre cette conversation"
});
